package org.ice.mp3listsetmaker.test.setlist;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Iterator;
import java.util.List;

import org.ice.media.m3u.MediaFile;
import org.ice.media.m3u.io.M3UWriter;
import org.ice.mp3listsetmaker.files.FileFinder;
import org.ice.mp3listsetmaker.setlist.TracksExtractor;
import org.junit.jupiter.api.Test;

class TracksExtractorTest {

	@Test
	void test() {
		List<String> list = TracksExtractor.extractTracks("{\n"
				+ "    \"id\": \"23b1183f\",\n"
				+ "    \"versionId\": \"g3f86d7f\",\n"
				+ "    \"eventDate\": \"12-10-2022\",\n"
				+ "    \"lastUpdated\": \"2022-10-13T12:28:03.000+0000\",\n"
				+ "    \"artist\": {\n"
				+ "      \"mbid\": \"eeb1195b-f213-4ce1-b28c-8565211f8e43\",\n"
				+ "      \"name\": \"Guns N’ Roses\",\n"
				+ "      \"sortName\": \"Guns N’ Roses\",\n"
				+ "      \"disambiguation\": \"American hard rock band from Los Angeles\",\n"
				+ "      \"url\": \"https://www.setlist.fm/setlists/guns-n-roses-7bd69e24.html\"\n"
				+ "    },\n"
				+ "    \"venue\": {\n"
				+ "      \"id\": \"63d636ff\",\n"
				+ "      \"name\": \"Estadio El Campín\",\n"
				+ "      \"city\": {\n"
				+ "        \"id\": \"3688689\",\n"
				+ "        \"name\": \"Bogotá\",\n"
				+ "        \"state\": \"Bogota D.C.\",\n"
				+ "        \"stateCode\": \"34\",\n"
				+ "        \"coords\": {\n"
				+ "          \"lat\": 4.6,\n"
				+ "          \"long\": -74.0833333\n"
				+ "        },\n"
				+ "        \"country\": {\n"
				+ "          \"code\": \"CO\",\n"
				+ "          \"name\": \"Colombia\"\n"
				+ "        }\n"
				+ "      },\n"
				+ "      \"url\": \"https://www.setlist.fm/venue/estadio-el-campin-bogota-colombia-63d636ff.html\"\n"
				+ "    },\n"
				+ "    \"tour\": {\n"
				+ "      \"name\": \"We're F'N Back! Tour 2022\"\n"
				+ "    },\n"
				+ "    \"sets\": {\n"
				+ "      \"set\": [\n"
				+ "        {\n"
				+ "          \"song\": [\n"
				+ "            {\n"
				+ "              \"name\": \"\",\n"
				+ "              \"tape\": true\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"It's So Easy\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Mr. Brownstone\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Chinese Democracy\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Slither\",\n"
				+ "              \"cover\": {\n"
				+ "                \"mbid\": \"3a528006-1429-47f4-ae9b-2ea95343e16a\",\n"
				+ "                \"name\": \"Velvet Revolver\",\n"
				+ "                \"sortName\": \"Velvet Revolver\",\n"
				+ "                \"disambiguation\": \"\",\n"
				+ "                \"url\": \"https://www.setlist.fm/setlists/velvet-revolver-13d689ad.html\"\n"
				+ "              }\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Welcome to the Jungle\",\n"
				+ "              \"info\": \"Link Wray's \\\"Rumble\\\" intro\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Better\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Double Talkin' Jive\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Live and Let Die\",\n"
				+ "              \"cover\": {\n"
				+ "                \"mbid\": \"d922d727-240a-4432-9a88-05a7cf9bc403\",\n"
				+ "                \"name\": \"Wings\",\n"
				+ "                \"sortName\": \"Wings\",\n"
				+ "                \"disambiguation\": \"Paul McCartney’s band\",\n"
				+ "                \"url\": \"https://www.setlist.fm/setlists/wings-23d68837.html\"\n"
				+ "              }\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Estranged\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Reckless Life\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Rocket Queen\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"You Could Be Mine\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Shadow of Your Love\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Attitude\",\n"
				+ "              \"cover\": {\n"
				+ "                \"mbid\": \"936addc3-91aa-49de-8ec0-0dc186de151f\",\n"
				+ "                \"name\": \"Misfits\",\n"
				+ "                \"sortName\": \"Misfits\",\n"
				+ "                \"disambiguation\": \"New Jersey punk band\",\n"
				+ "                \"url\": \"https://www.setlist.fm/setlists/misfits-73d68ed5.html\"\n"
				+ "              },\n"
				+ "              \"info\": \"Duff on lead vocals\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Absurd\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Hard Skool\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Civil War\",\n"
				+ "              \"info\": \"Jimi Hendrix's \\\"Machine Gun\\\" outro\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Sorry\",\n"
				+ "              \"info\": \"followed by band intros\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Slash Guitar Solo\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Sweet Child o' Mine\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"November Rain\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Wichita Lineman\",\n"
				+ "              \"cover\": {\n"
				+ "                \"mbid\": \"04e296d1-ab98-46e9-ba88-a42b5024e518\",\n"
				+ "                \"name\": \"Jimmy Webb\",\n"
				+ "                \"sortName\": \"Webb, Jimmy\",\n"
				+ "                \"disambiguation\": \"US songwriter, composer, producer, pianist & singer\",\n"
				+ "                \"url\": \"https://www.setlist.fm/setlists/jimmy-webb-bd75126.html\"\n"
				+ "              }\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Knockin' on Heaven's Door\",\n"
				+ "              \"cover\": {\n"
				+ "                \"mbid\": \"72c536dc-7137-4477-a521-567eeb840fa8\",\n"
				+ "                \"name\": \"Bob Dylan\",\n"
				+ "                \"sortName\": \"Dylan, Bob\",\n"
				+ "                \"disambiguation\": \"\",\n"
				+ "                \"url\": \"https://www.setlist.fm/setlists/bob-dylan-1bd6adb8.html\"\n"
				+ "              }\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Nightrain\"\n"
				+ "            }\n"
				+ "          ]\n"
				+ "        },\n"
				+ "        {\n"
				+ "          \"encore\": 1,\n"
				+ "          \"song\": [\n"
				+ "            {\n"
				+ "              \"name\": \"Coma\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Patience\",\n"
				+ "              \"info\": \"The Beatles' \\\"Blackbird\\\" intro\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Don't Cry\"\n"
				+ "            },\n"
				+ "            {\n"
				+ "              \"name\": \"Paradise City\"\n"
				+ "            }\n"
				+ "          ]\n"
				+ "        }\n"
				+ "      ]\n"
				+ "    },\n"
				+ "    \"url\": \"https://www.setlist.fm/setlist/guns-n-roses/2022/estadio-el-campin-bogota-colombia-23b1183f.html\"\n"
				+ "  }");
		
		for (Iterator<String> iterator = list.iterator(); iterator.hasNext();) {
			String string = (String) iterator.next();
			System.out.println(string);
		}
		
		List<MediaFile> mediaFiles = FileFinder.findMediaFiles(list, "/mnt/datos/etc/mi musica/Guns n' Roses/");
		
		for (Iterator<MediaFile> iterator = mediaFiles.iterator(); iterator.hasNext();) {
			MediaFile mediaFile =  iterator.next();
			System.out.println(String.format("%s - %s", mediaFile.getName(), mediaFile.getUrl()));
		}
		
		try {
			M3UWriter.writeList(true, true, "/", "guns.m3u", mediaFiles);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
